#! /usr/bin/env python
# -*- coding: utf-8 -*-

import rospy

from mhr2300_driver import magnetometer

def main():
    rospy.init_node('mhr2300_driver')

    mag = magnetometer.Magnetometer()
    mag.init_acquisition()
    rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
